default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: inventory_development

test:
  <<: *default
  database: inventory_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_URL") %>
